name: Golden Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit  # <--- WE ARE INSTALLING THE SECURITY TOOL HERE

      # --- NEW STEP STARTS HERE ---
      - name: Run SAST Scan (Bandit)
        run: bandit -r app.py -f json -o bandit-report.json || true
      # Note: '|| true' prevents the pipeline from stopping immediately so we can see the results.
      # In a real strict pipeline, you might remove '|| true' to block the build.

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        if: always() # Run this even if the scan found issues
        with:
          name: bandit-report
          path: bandit-report.json
      # --- NEW STEP ENDS HERE ---

      # --- NEW STEP: Scan Dependencies with Trivy ---
      - name: Run Trivy Vulnerability Scanner (FS)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0' # Keep 0 for now so we can see the results without breaking the build
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


      - name: Install App Requirements
        run: pip install -r requirements.txt

      - name: Build Docker Image
        run: docker build -t golden-app .
          
        # --- NEW STEP: Scan the Container Image ---
      - name: Run Trivy Vulnerability Scanner (Image)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'golden-app:${{ github.sha }}' # Scanning the image we just built
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'